package ru.klapatnyuk.sberbank.web.key;

import ru.klapatnyuk.sberbank.web.i18n.ResourceKey;

/**
 * @author klapatnyuk
 */
public enum NotificationKey implements ResourceKey {

    ERROR_DESCRIPTION_TIME,
    ERROR_DESCRIPTION_BUSINESS,
    ERROR_DESCRIPTION_BUSINESS_TIME,

    SESSION_EXPIRED_CAPTION,
    SESSION_EXPIRED,
    COMMUNICATION_PROBLEM_CAPTION,
    COMMUNICATION_PROBLEM,
    AUTHENTICATION_PROBLEM_CAPTION,
    AUTHENTICATION_PROBLEM,
    INTERNAL_ERROR_CAPTION,
    INTERNAL_ERROR,
    COOKIES_DISABLED_CAPTION,
    COOKIES_DISABLED,

    LOGIN_ERROR,
    LOGIN_INVALID,
    LOGIN_CONNECT_ERROR,

    ENTITY_TITLE_EMPTY_VALIDATE,
    ENTITY_TITLE_UNIQUE_VALIDATE,

    DOCUMENT_TEMPLATE_VALIDATE,

    TEMPLATE_FIELDS_REQUIRED,
    TEMPLATE_FIELD_TITLE_UNIQUE_VALIDATE,
    TEMPLATE_FIELDS_ALL_REQUIRED;

    @Override
    public String getKey() {
        return "noti." + ResourceKey.convert(this);
    }
}
