package ru.klapatnyuk.sberbank.web.key;

import ru.klapatnyuk.sberbank.web.i18n.ResourceKey;

/**
 * @author klapatnyuk
 */
public enum NotificationKey implements ResourceKey {

    ERROR_DESCRIPTION_TIME,
    ERROR_DESCRIPTION_BUSINESS,
    ERROR_DESCRIPTION_BUSINESS_TIME,

    SESSION_EXPIRED_CAPTION,
    SESSION_EXPIRED,
    COMMUNICATION_PROBLEM_CAPTION,
    COMMUNICATION_PROBLEM,
    AUTHENTICATION_PROBLEM_CAPTION,
    AUTHENTICATION_PROBLEM,
    INTERNAL_ERROR_CAPTION,
    INTERNAL_ERROR,
    COOKIES_DISABLED_CAPTION,
    COOKIES_DISABLED,

    LOGIN_FAILED,
    LOGIN_ERROR,
    LOGIN_INVALID,

    ENTITY_TITLE_EMPTY_VALIDATE,
    ENTITY_TITLE_UNIQUE_VALIDATE,

    DOCUMENT_TEMPLATE_VALIDATE,
    DOCUMENT_GET_ERROR,
    DOCUMENT_FIELD_GET_ERROR,
    DOCUMENT_CREATE_ERROR,
    DOCUMENT_UPDATE_ERROR,
    DOCUMENT_REMOVE_ERROR,
    DOCUMENT_CREATED,
    DOCUMENT_UPDATED,
    DOCUMENT_REMOVED,

    TEMPLATE_FIELDS_REQUIRED,
    TEMPLATE_FIELD_TITLE_UNIQUE_VALIDATE,
    TEMPLATE_FIELDS_ALL_REQUIRED,
    TEMPLATE_GET_ERROR,
    TEMPLATE_FIELD_GET_ERROR,
    TEMPLATE_CREATE_ERROR,
    TEMPLATE_UPDATE_ERROR,
    TEMPLATE_REMOVE_ERROR,
    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_REMOVED;

    @Override
    public String getKey() {
        return "noti." + ResourceKey.convert(this);
    }
}
